services:
  # Grafana - Graphical data visualization for InfluxDB data
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - default
    ports:
      - "$GRAFANA_PORT:3000"
    user: $PUID
    volumes:
      - $DOCKERDIR/appdata/grafana:/var/lib/grafana
    environment:
        GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
        GF_AUTH_GENERIC_OAUTH_NAME: "authentik"
        GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "RTzCAKumQrsGPBYFUjKGMZHnOAMpcc5FJg3pV3jS"
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: "nPYiUoGWFGajFjhYhJUO95rGwVwVZfyGKg5fIF7zA475glcCRrinmaMeXHZVvPjjgmxN9hIIFBrOatV6fAPdED5C3xUZG023SCxHBkCopdfbLItUSYLXUlNapxZVEbX0"
        GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
        GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://authentik.purosurccd.com/application/o/authorize/"
        GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://authentik.purosurccd.com/application/o/token/"
        GF_AUTH_GENERIC_OAUTH_API_URL: "https://authentik.purosurccd.com/application/o/userinfo/"
        GF_AUTH_SIGNOUT_REDIRECT_URL: "https://authentik.purosurccd.com/application/o/grafana/end-session/"
        # Optionally enable auto-login (bypasses Grafana login screen)
        GF_AUTH_OAUTH_AUTO_LOGIN: "true"
        # Optionally map user groups to Grafana roles
        GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
        # Required if Grafana is running behind a reverse proxy
        GF_SERVER_ROOT_URL: "https://grafana.purosurccd.com"
        GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource,grafana-worldmap-panel,grafana-piechart-panel,cloudflare-app"
    # DOCKER-LABELS-PLACEHOLDER