services:
  # Uptime Kuma - Status Page & Monitoring Server
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - default
      - socket_proxy
    ports:
      - "$UPTIMEKUMA_PORT:3001"
    volumes:
      - $DOCKERDIR/appdata/uptime-kuma:/app/data